"""added add adn list coaches fixes

Revision ID: 09fc77861fe1
Revises: 7565d3673679
Create Date: 2020-05-17 16:30:56.204369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fc77861fe1'
down_revision = '7565d3673679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coaches', type_='foreignkey')
    op.drop_column('coaches', 'runner_id')
    op.add_column('runners', sa.Column('coach_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'runners', 'coaches', ['coach_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runners', type_='foreignkey')
    op.drop_column('runners', 'coach_id')
    op.add_column('coaches', sa.Column('runner_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'coaches', 'runners', ['runner_id'], ['id'])
    # ### end Alembic commands ###
