"""added owern last name

Revision ID: 7565d3673679
Revises: 94323d6c83e2
Create Date: 2020-05-17 15:42:03.860771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7565d3673679'
down_revision = '94323d6c83e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('lastname', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'lastname')
    # ### end Alembic commands ###
